#!/usr/bin/python3
def factorize(n):
    for i in range(2, int(n**0.5) + 1):
        if n % i:
            continue
        return i, n // i
    return 1, n

def main():
    import sys
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>")
        return

    with open(sys.argv[1], 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print(f"{n}={p}*{q}")

if __name__ == "__main__":
    main()

