#!/usr/bin/python3
from sys import argv


def factorize(value):
	i = 2
	n=1;
	if value < 2:
		return
	while value % i:
		i += 1
		n = value // i
	print(f"{value}={n}*{i}")

if len(argv) != 2:
	exit()

try:
	with open(argv[1]) as file:
		line = file.readline()

		while line != "":
			value = int(line.split('\n')[0])
			factorize(value)
			line = file.readline()
except:
	pass
