#!/usr/bin/env python3
import subprocess
from collections import Counter
def find_factors(n, factors):
    factor_count = Counter(factors)
    exponents = [(factor, count) for factor, count in factor_count.items()]
    p=int(exponents[0][0])**int(exponents[0][1])
    q=int(n)//p
    print(f"{n}={q}*{p}")

if __name__ == "__main__":
	import sys

	if len(sys.argv) != 2:
		print(f"Usage: {sys.argv[0]} <file>")
		sys.exit(1)

	input_file = sys.argv[1]
	try:
		with open(input_file, 'r') as file:
			for line in file:
				n = line.strip()
				if not n:
					continue
				prcss = subprocess.check_output(["factor", n])
				result = prcss.decode('utf-8').strip()
				factorslist = result.split(': ')
				if len(factorslist) < 2:
					print(f"{n} not a RSA number")
				else :
					factors=factorslist[1].split()
					p = factors[0]
					if p == n:
						print(f"{n} not a RSA number")
					else:
						find_factors(n, factors)
	except FileNotFoundError:
		print(f"Error: File '{input_file}' not found.")
	except Exception as e:
		print(f"An error occurred: {e}")
