#!/usr/bin/env python3
import subprocess

if __name__ == "__main__":
	import sys

	if len(sys.argv) != 2:
		print(f"Usage: {sys.argv[0]} <file>")
		sys.exit(1)

	input_file = sys.argv[1]
	try:
		with open(input_file, 'r') as file:
			for line in file:
				n = line.strip()
				if not n:
					continue
				prcss = subprocess.check_output(["factor", n])
				result = prcss.decode('utf-8').strip()
				factorslist = result.split(': ')
				if len(factorslist) < 2:
					print(f"{n} not a RSA number")
				else :
					factors=factorslist[1].split()
					p = factors[0]
					if p == n:
						print(f"{n} not a RSA number")
					else:
						q = int(n)// int(p)
						print(f"{n}={q}*{p}")
	except FileNotFoundError:
		print(f"Error: File '{input_file}' not found.")
	except Exception as e:
		print(f"An error occurred: {e}")
